name: Checks

on: [push, pull_request]

jobs:
  test-lint:
    name: Test, Wait for DB, and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Start Containers
        run: docker compose up -d --build db

      - name: Wait for Database
        run: docker compose run --rm app sh -c "python manage.py wait_for_db"

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py test"

      - name: Run Lint
        run: docker compose run --rm app sh -c "flake8"

      - name: Stop Containers
        if: always()
        run: docker compose down
